title: De Plantuh Man | For the Growth of The Nation
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    has_social: true
    links: []
  header:
    has_nav: true
    logo_img: ''
    title: De Plantuh Man
  layout_style: grid
  palette: red
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
