title: De Plantuh Man | For the Growth of The Nation
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    logo_img: ''
    title: De Plantuh Man
  layout_style: list
  palette: red
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
